version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # should update version number in package.json  and package-lock.json
    versioning-strategy: increase 