trigger:
- master          # Trigger a build when master is modified

pr:
  drafts: false   # For GitHub only, whether to build draft PRs, defaults to true
  branches:
    include:
      - master      # Will trigger a build on a PR on master

resources:
  repositories:
    - repository: build-pipeline-scripts
      type: git
      ref: master
      name: iModelTechnologies/imodeljs-build-pipeline-scripts
      
stages:
- stage: Build
  displayName: Build
  
  jobs:
    - job: BuildPackages  # Build on linux, mac, windows
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          mac:
            imageName: 'macos-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName) # Which pool to use for the job
      steps:
      - bash: |
          # Secret variables must follow this recipe :
          #   1. Set in the "Variables" tab in Azure Pipelines UI with a slightly different name ( here, we dropped "imjs" from each one)
          #   2. Use this bash script step to first set secret variable values in a temporary variable (see env:)
          #   3. Use the ##vso[task.setvariable command as below, to use the temporary variable to then set the secret value to the correct variable name in a more global scope.
          #  This is done so that we can keep the values secret within the build pipeline but then decrypt them in the environment when actually running the tests.
          #   > A better solution would be to figure out how to decrypt in Node itself
          echo "##vso[task.setvariable variable=IMJS_TEST_REGULAR_USER_PASSWORD;]$reg_user_pass"
          echo "##vso[task.setvariable variable=IMJS_TEST_MANAGER_USER_PASSWORD;]$manager_user_pass"
        displayName: 'Add config to environment'
        env:
          manager_user_pass : $(TEST_MANAGER_USER_PASSWORD)
          reg_user_pass : $(TEST_REGULAR_USER_PASSWORD)
      - script: npm install
        displayName: 'Install dependencies'

      - script: npm run build
        displayName: 'Build'

      - script: npm run lint
        displayName: 'Lint'

      # integration tests
      - script: npm run test:integration
        displayName: npm run test:integration

      - script: npm pack
        displayName: 'Pack'

      # publish artifact
      - bash: |
          realityDataClientVersion=$(node -p "require('./package.json').version")
          realityDataClientName=$(node -p "require('./package.json').name")
          checkVer() {
            localVer=$1
            name=$2
            remoteVer=$(npm view $name version)
            if [ -z "$remoteVer" ]; then
              # $remoteVer is null or empty
              remoteVer=0.0.0
            fi
            olderVer=$(printf '%s\n' "$localVer" "$remoteVer" | sort -V | head -n1)
            if [ "$localVer" != "$remoteVer" ] && [ "$remoteVer" = "$olderVer" ]; then
              echo true
            else
              echo false
            fi
          }
          updateClient=$(checkVer $realityDataClientVersion $realityDataClientName)
          if [ "$updateClient" = "true" ]; then
            echo "package publishing conditions are met."
            shouldPublish=true
          else
            echo "package publishing conditions not met."
            shouldPublish=false
          fi
          echo "##vso[task.setvariable variable=shouldPublish;isOutput=true]$shouldPublish"
          echo "##vso[task.setvariable variable=realityDataClientVersion;isOutput=true]$realityDataClientVersion"
          echo "##vso[task.setvariable variable=realityDataClientName;isOutput=true]$realityDataClientName"
        displayName: 'Store Build Info'
        name: info
        condition: and(succeeded(), eq(variables.try_publish, true), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Agent.OS'], 'Linux'))
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/itwin-reality-data-client-$(info.realityDataClientVersion).tgz'
          artifactName: RealityDataClient
        displayName: 'Publish Reality Data client'
        condition: and(succeeded(), eq(variables['info.shouldPublish'], 'true'))

- stage: Publish
  displayName: Publish
  condition: and(succeeded(), eq(dependencies.Build.outputs['BuildPackages.linux.info.shouldPublish'], 'true'))
  dependsOn: Build

  jobs:
    - template: templates/npmjs-publish-deployment.yaml@build-pipeline-scripts
      parameters:
        path: '*.tgz'
        artifactName: RealityDataClient
        name: RealityDataClient
