trigger:
- master          # Trigger a build when master is modified

pr:
  drafts: false   # For GitHub only, whether to build draft PRs, defaults to true
  branches:
    include:
      - master      # Will trigger a build on a PR on master

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: BuildPackages  # Build on linux, mac, windows
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          mac:
            imageName: 'macos-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName) # Which pool to use for the job
      steps:
      - script: npm install
        displayName: 'Install dependencies'

      - script: npm run build
        displayName: 'Build'

      - script: npm run lint
        displayName: 'Lint'

      - script: npm pack
        displayName: 'Pack'

