name: Publish itwin/reality-data-client to NPM

on: workflow_dispatch

jobs:
  ci:
    uses: itwin/reality-data-client/.github/workflows/ci.yaml@arun/reuse-pipeline

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin 

      - name: Publish packages
        run: |
          npm run publish-packages -y --branch ${{ github.ref_name }} --message "Version bump [skip actions]"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}