name: Publish itwin/reality-data-client to NPM

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: CI
        uses: itwin/reality-data-client/.github/workflows/ci.yaml@master

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin 

      - name: Publish packages
        run: |
          npm run publish-packages -y --branch ${{ github.ref_name }} --message "Version bump [skip actions]"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}